### ISSUE TITLE
Updates required for new python/django

### ISSUE THREAD

**Issue by marksweb** [nephila/django-app-helper#204]
## Description

Updates to the app are required for new python/django so that apps which depend on this application can continue to develop.

I've made a start on this, but require an issue to reference in my branch.

## Proposed solution

Update tox/github workflows & then take it from there.

**Comment by marksweb** [comment]
Trying to get tests passing on this branch; https://github.com/marksweb/django-app-helper/tree/feature/204-upgrades

**Comment by marksweb** [comment]
The `nocms` tests appear to be causing test suite failures because of `ImportError` on cms.

I didn't expect to need to fix anything around that given that's how the test suite has been running previously 🤔

**Comment by pietzschke** [comment]
Looks like a circular import error: https://github.com/pietzschke/django-app-helper/runs/5187464956?check_suite_focus=true
The tests use the current filer version? How will they ever go through?

**Comment by pietzschke** [comment]
@marksweb i would say we need a new version on filer first, using the gettext_lazy functions:
https://docs.djangoproject.com/en/3.0/releases/3.0/#id3

But the tests on cms maybe fail anyway 🤔

**Comment by marksweb** [comment]
@pietzschke Yes, I thought that a release of django-filer that brings some of the changes in, without going as far as my django 4 support which might break things as it has to drop support.

I don't think I've done it on django-filer yet, but I've been putting pre-commit hooks on projects that belong to the [django-cms association](https://github.com/django-cms). Two of the hooks I've been using are py-upgrade and django-upgrade. If we're looking at moving support django >=2.2 I think running these hooks will make upgrades an automated process. Support for python 3.6 also needs to go as it's EOL so py-upgrade can be targeted at >=3.7 to bring the python up to date.

**Comment by pietzschke** [comment]
@marksweb  Okay great, i will try to add the pre-commit hooks tomorrow, run them and include the code locally for testing in the app helper. I will let you know ✌️

**Comment by yakky** [comment]
@marksweb @pietzschke sorry for the long delay, I will tackle this really soon to get this application back on track

**Comment by marksweb** [comment]
@yakky No need to apologise. If we can help out with this or any of your other cms apps, let me know & I'll reach out to the cms core team.
