### ISSUE TITLE
Bug: django-app-helper test does not process --runner-options properly

### ISSUE THREAD

**Issue by florianschieder** [nephila/django-app-helper#220]
We use `django-app-helper` to run our tests. Some of them are not properly working within the `django-app-helper` environment so I tried to exclude them by passing `--exclude-tag ...` to `--runner-options`.

Unfortunately, it seems like `django-app-helper`  generally does not pass `--runner-options` to the test runner properly because running `django-app-helper <APP> test --runner-options="foo"` results in the following output:

`usage: django-app-helper [-h] [-t TOP_LEVEL] [-p PATTERN] [--keepdb] [-r] [--debug-mode] [-d] [--parallel [N]] [--tag TAGS] [--exclude-tag EXCLUDE_TAGS] [--pdb] [-b]`
`                         [--no-faulthandler] [--timing] [-k TEST_NAME_PATTERNS]`
`django-app-helper: error: unrecognized arguments: f o o`

Same goes for `--runner-options="--exclude-tag someTag"`
→ `django-app-helper: error: unrecognized arguments: - - e x c l u d e - t a g   s o m e T a g`

We are using django-app-helper 3.2.0.

**Comment by yakky** [comment]
@florianschieder thanks for reporting this

PR #221 should fix the issue: can you test the branch in your local setup?

**Comment by yakky** [comment]
@florianschieder no worries. Enjoy your time off!

**Comment by florianschieder** [comment]
Hello @yakky, please excuse the delay. I will immediately take a look at testing this.

**Comment by florianschieder** [comment]
@yakky: I installed `(django-app-helper) → bugfix/issue-220-runner-options` and could not reproduce the issue.
Thank you very much for the quick fix and please apologize my late reply.
Can you predict when this fix will be published into a bugfix release?
