### ISSUE TITLE
Check Django5.0 / Python 3.12 compatibility

### ISSUE THREAD

**Issue by protoroto** [nephila/django-app-helper#244]
## Description

We need to check Django5.0 and Python3.12 compatibility

**Comment by fsbraun** [comment]
@protoroto Any idea when this will be released? I'd love to start testing my downstream packages...

**Comment by protoroto** [comment]
@fsbraun Hi! I have to discuss this with @yakky , but I guess we'll wait for an official Django 5.0 release before releasing this (it should be somewhere in December 2023 according to their release notes)

**Comment by fsbraun** [comment]
Sure. django 5 is a RC now/yesterday. So there are no big changes to be expected until December. We could however, run tests on our packages, which right now fail due to django-app-helper.

**Comment by protoroto** [comment]
@fsbraun I'll discuss this with @yakky and get back to you as soon as possible!

**Comment by yakky** [comment]
@fsbraun any plan for django 5 compatibility in django CMS 3.11?

We would like to make a proper release once django CMS 3 supports Django 5, but we can make an intermediate release if it's useful for other applications

**Comment by protoroto** [comment]
@fsbraun Hi! I've just released version 3.3.3 with Django 5 support

**Comment by fsbraun** [comment]
Thanks so much, @protoroto !!
