### ISSUE TITLE
Support for tagged tests

### ISSUE THREAD

**Issue by dkellner** [nephila/django-app-helper#92]
It seems [tagging tests](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#tagging-tests) is not supported yet. Is this a planned/desired feature or outside the scope of this helper? I've tried passing `--exclude-tag=slow` via `--runner-options` to no avail.

**Comment by yakky** [comment]
@dkellner definitely they are in scope. I have had no time so far to look into them. Any help / suggestion is welcome!

**Comment by yakky** [comment]
@dkellner it took me exactly three years to handle this :sweat: 
but we're not finally able to use tags (and any other test runner options)
